create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text unique,
  display_name text not null default 'Hero',
  avatar_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.player_saves (
  user_id uuid primary key references public.profiles (id) on delete cascade,
  save_data jsonb not null default '{}'::jsonb,
  revision bigint not null default 1,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  last_synced_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.player_public_stats (
  user_id uuid primary key references public.profiles (id) on delete cascade,
  hero_name text not null default 'Hero',
  hero_level integer not null default 1 check (hero_level >= 1),
  total_gold bigint not null default 0 check (total_gold >= 0),
  combat_power bigint not null default 0 check (combat_power >= 0),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.clans (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9-]{3,32}$'),
  name text not null unique check (char_length(name) between 3 and 40),
  description text not null default '',
  owner_user_id uuid not null references public.profiles (id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.clan_members (
  clan_id uuid not null references public.clans (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  role text not null default 'member' check (role in ('owner', 'officer', 'member')),
  joined_at timestamptz not null default timezone('utc', now()),
  primary key (clan_id, user_id)
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  channel_kind text not null check (channel_kind in ('global', 'market', 'clan', 'system')),
  clan_id uuid references public.clans (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  author_name text not null,
  body text not null check (char_length(btrim(body)) between 1 and 500),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  constraint clan_chat_requires_clan
    check (
      (channel_kind = 'clan' and clan_id is not null) or
      (channel_kind in ('global', 'market', 'system') and clan_id is null)
    )
);

create or replace function public.is_clan_admin(p_clan_id uuid, p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.clan_members cm
    where cm.clan_id = p_clan_id
      and cm.user_id = p_user_id
      and cm.role in ('owner', 'officer')
  );
$$;

create index if not exists idx_player_public_stats_level on public.player_public_stats (hero_level desc, updated_at desc);
create index if not exists idx_chat_messages_channel_time on public.chat_messages (channel_kind, created_at desc);
create index if not exists idx_chat_messages_clan_time on public.chat_messages (clan_id, created_at desc) where clan_id is not null;
create index if not exists idx_clan_members_user on public.clan_members (user_id);

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

drop trigger if exists set_player_saves_updated_at on public.player_saves;
create trigger set_player_saves_updated_at
before update on public.player_saves
for each row
execute function public.set_updated_at();

drop trigger if exists set_player_public_stats_updated_at on public.player_public_stats;
create trigger set_player_public_stats_updated_at
before update on public.player_public_stats
for each row
execute function public.set_updated_at();

drop trigger if exists set_clans_updated_at on public.clans;
create trigger set_clans_updated_at
before update on public.clans
for each row
execute function public.set_updated_at();

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  next_name text;
begin
  next_name := coalesce(
    nullif(new.raw_user_meta_data ->> 'full_name', ''),
    nullif(new.raw_user_meta_data ->> 'name', ''),
    nullif(split_part(coalesce(new.email, ''), '@', 1), ''),
    'Hero'
  );

  insert into public.profiles (id, email, display_name, avatar_url)
  values (
    new.id,
    new.email,
    next_name,
    nullif(new.raw_user_meta_data ->> 'avatar_url', '')
  )
  on conflict (id) do update
    set email = excluded.email,
        display_name = coalesce(nullif(public.profiles.display_name, ''), excluded.display_name),
        avatar_url = coalesce(public.profiles.avatar_url, excluded.avatar_url),
        updated_at = timezone('utc', now());

  insert into public.player_saves (user_id)
  values (new.id)
  on conflict (user_id) do nothing;

  insert into public.player_public_stats (user_id, hero_name)
  values (new.id, next_name)
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_auth_user();

insert into public.profiles (id, email, display_name, avatar_url)
select
  u.id,
  u.email,
  coalesce(
    nullif(u.raw_user_meta_data ->> 'full_name', ''),
    nullif(u.raw_user_meta_data ->> 'name', ''),
    nullif(split_part(coalesce(u.email, ''), '@', 1), ''),
    'Hero'
  ),
  nullif(u.raw_user_meta_data ->> 'avatar_url', '')
from auth.users u
on conflict (id) do update
  set email = excluded.email,
      avatar_url = coalesce(public.profiles.avatar_url, excluded.avatar_url),
      updated_at = timezone('utc', now());

insert into public.player_saves (user_id)
select id from public.profiles
on conflict (user_id) do nothing;

insert into public.player_public_stats (user_id, hero_name)
select
  p.id,
  coalesce(nullif(p.display_name, ''), 'Hero')
from public.profiles p
on conflict (user_id) do nothing;

alter table public.profiles enable row level security;
alter table public.player_saves enable row level security;
alter table public.player_public_stats enable row level security;
alter table public.clans enable row level security;
alter table public.clan_members enable row level security;
alter table public.chat_messages enable row level security;

create policy "profiles_select_authenticated"
on public.profiles
for select
to authenticated
using (true);

create policy "profiles_insert_self"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

create policy "profiles_update_self"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "player_saves_select_self"
on public.player_saves
for select
to authenticated
using (auth.uid() = user_id);

create policy "player_saves_insert_self"
on public.player_saves
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "player_saves_update_self"
on public.player_saves
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "player_public_stats_select_authenticated"
on public.player_public_stats
for select
to authenticated
using (true);

create policy "player_public_stats_insert_self"
on public.player_public_stats
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "player_public_stats_update_self"
on public.player_public_stats
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "clans_select_authenticated"
on public.clans
for select
to authenticated
using (true);

create policy "clans_insert_owner"
on public.clans
for insert
to authenticated
with check (auth.uid() = owner_user_id);

create policy "clans_update_owner"
on public.clans
for update
to authenticated
using (auth.uid() = owner_user_id)
with check (auth.uid() = owner_user_id);

create policy "clans_delete_owner"
on public.clans
for delete
to authenticated
using (auth.uid() = owner_user_id);

create policy "clan_members_select_authenticated"
on public.clan_members
for select
to authenticated
using (true);

create policy "clan_members_insert_self_or_admin"
on public.clan_members
for insert
to authenticated
with check (
  auth.uid() = user_id
  or public.is_clan_admin(clan_id, auth.uid())
);

create policy "clan_members_update_admin"
on public.clan_members
for update
to authenticated
using (public.is_clan_admin(clan_id, auth.uid()))
with check (public.is_clan_admin(clan_id, auth.uid()));

create policy "clan_members_delete_self_or_admin"
on public.clan_members
for delete
to authenticated
using (
  auth.uid() = user_id
  or public.is_clan_admin(clan_id, auth.uid())
);

create policy "chat_messages_select_authenticated"
on public.chat_messages
for select
to authenticated
using (
  channel_kind <> 'clan'
  or exists (
    select 1
    from public.clan_members cm
    where cm.clan_id = chat_messages.clan_id
      and cm.user_id = auth.uid()
  )
);

create policy "chat_messages_insert_authenticated"
on public.chat_messages
for insert
to authenticated
with check (
  auth.uid() = user_id
  and author_name <> ''
  and (
    channel_kind in ('global', 'market', 'system')
    or exists (
      select 1
      from public.clan_members cm
      where cm.clan_id = chat_messages.clan_id
        and cm.user_id = auth.uid()
    )
  )
);
