create table if not exists public.private_messages (
  id bigint generated by default as identity primary key,
  sender_user_id uuid not null references public.profiles (id) on delete cascade,
  recipient_user_id uuid not null references public.profiles (id) on delete cascade,
  sender_name text not null,
  recipient_name text not null,
  sender_avatar text,
  recipient_avatar text,
  body text not null check (char_length(btrim(body)) between 1 and 500),
  read_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  constraint private_messages_no_self check (sender_user_id <> recipient_user_id)
);

create index if not exists idx_private_messages_sender_time
on public.private_messages (sender_user_id, created_at desc);

create index if not exists idx_private_messages_recipient_time
on public.private_messages (recipient_user_id, created_at desc);

alter table public.private_messages enable row level security;

create or replace function public.private_messages_read_at_only()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.id <> old.id
    or new.sender_user_id <> old.sender_user_id
    or new.recipient_user_id <> old.recipient_user_id
    or new.sender_name <> old.sender_name
    or new.recipient_name <> old.recipient_name
    or coalesce(new.sender_avatar, '') <> coalesce(old.sender_avatar, '')
    or coalesce(new.recipient_avatar, '') <> coalesce(old.recipient_avatar, '')
    or new.body <> old.body
    or new.created_at <> old.created_at then
    raise exception 'Only read_at can be updated.';
  end if;
  return new;
end;
$$;

drop trigger if exists private_messages_read_at_only on public.private_messages;
create trigger private_messages_read_at_only
before update on public.private_messages
for each row execute function public.private_messages_read_at_only();

drop policy if exists "private_messages_select_participants" on public.private_messages;
create policy "private_messages_select_participants"
on public.private_messages
for select
to authenticated
using (auth.uid() = sender_user_id or auth.uid() = recipient_user_id);

drop policy if exists "private_messages_insert_sender" on public.private_messages;
create policy "private_messages_insert_sender"
on public.private_messages
for insert
to authenticated
with check (
  auth.uid() = sender_user_id
  and sender_user_id <> recipient_user_id
  and sender_name <> ''
  and recipient_name <> ''
);

drop policy if exists "private_messages_update_read_recipient" on public.private_messages;
create policy "private_messages_update_read_recipient"
on public.private_messages
for update
to authenticated
using (auth.uid() = recipient_user_id)
with check (auth.uid() = recipient_user_id);
