create table if not exists public.premium_wallets (
  user_id uuid primary key references public.profiles (id) on delete cascade,
  dark_stones bigint not null default 0 check (dark_stones >= 0),
  lifetime_purchased bigint not null default 0 check (lifetime_purchased >= 0),
  lifetime_spent bigint not null default 0 check (lifetime_spent >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.premium_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  kind text not null check (kind in ('purchase', 'spend', 'refund', 'grant', 'adjustment')),
  currency text not null default 'dark_stone',
  amount bigint not null check (amount <> 0),
  balance_after bigint not null default 0 check (balance_after >= 0),
  source text not null default 'system',
  source_ref text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists idx_premium_transactions_unique_source_ref
  on public.premium_transactions (source, source_ref)
  where source_ref is not null;

create index if not exists idx_premium_transactions_user_time
  on public.premium_transactions (user_id, created_at desc);

create table if not exists public.premium_checkout_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  provider text not null default 'stripe',
  package_id text not null,
  currency text not null default 'usd',
  amount_cents integer not null check (amount_cents >= 0),
  dark_stones bigint not null check (dark_stones > 0),
  status text not null default 'created' check (status in ('created', 'pending', 'completed', 'expired', 'failed')),
  stripe_session_id text unique,
  stripe_payment_intent_id text,
  checkout_url text,
  metadata jsonb not null default '{}'::jsonb,
  fulfilled_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_premium_checkout_sessions_user_time
  on public.premium_checkout_sessions (user_id, created_at desc);

alter table public.premium_wallets enable row level security;
alter table public.premium_transactions enable row level security;
alter table public.premium_checkout_sessions enable row level security;

drop policy if exists premium_wallets_select_own on public.premium_wallets;
create policy premium_wallets_select_own
on public.premium_wallets
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists premium_transactions_select_own on public.premium_transactions;
create policy premium_transactions_select_own
on public.premium_transactions
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists premium_checkout_sessions_select_own on public.premium_checkout_sessions;
create policy premium_checkout_sessions_select_own
on public.premium_checkout_sessions
for select
to authenticated
using (auth.uid() = user_id);

drop trigger if exists set_premium_wallets_updated_at on public.premium_wallets;
create trigger set_premium_wallets_updated_at
before update on public.premium_wallets
for each row
execute function public.set_updated_at();

drop trigger if exists set_premium_checkout_sessions_updated_at on public.premium_checkout_sessions;
create trigger set_premium_checkout_sessions_updated_at
before update on public.premium_checkout_sessions
for each row
execute function public.set_updated_at();

insert into public.premium_wallets (user_id)
select p.id
from public.profiles p
on conflict (user_id) do nothing;
