create table if not exists public.parties (
  id uuid primary key default gen_random_uuid(),
  leader_user_id uuid not null references public.profiles (id) on delete cascade,
  name text not null check (char_length(btrim(name)) between 3 and 40),
  visibility text not null default 'private' check (visibility in ('private', 'open')),
  state text not null default 'forming' check (state in ('forming', 'active', 'disbanded')),
  activity text not null default 'Idle' check (char_length(btrim(activity)) between 1 and 60),
  min_level integer not null default 1 check (min_level >= 1),
  max_members integer not null default 4 check (max_members between 2 and 4),
  auto_accept_requests boolean not null default false,
  locked boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  disbanded_at timestamptz
);

create table if not exists public.party_members (
  party_id uuid not null references public.parties (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  role text not null default 'member' check (role in ('leader', 'member')),
  ready boolean not null default false,
  joined_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (party_id, user_id)
);

create unique index if not exists idx_party_members_user_unique
on public.party_members (user_id);

create table if not exists public.party_invites (
  id uuid primary key default gen_random_uuid(),
  party_id uuid not null references public.parties (id) on delete cascade,
  from_user_id uuid not null references public.profiles (id) on delete cascade,
  to_user_id uuid not null references public.profiles (id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'declined', 'revoked', 'expired')),
  created_at timestamptz not null default timezone('utc', now()),
  expires_at timestamptz not null default (timezone('utc', now()) + interval '15 minutes'),
  responded_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  constraint party_invites_no_self check (from_user_id <> to_user_id)
);

create unique index if not exists idx_party_invites_pending_target
on public.party_invites (party_id, to_user_id)
where status = 'pending';

create index if not exists idx_party_invites_to_user
on public.party_invites (to_user_id, status, created_at desc);

create table if not exists public.party_join_requests (
  id uuid primary key default gen_random_uuid(),
  party_id uuid not null references public.parties (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'cancelled', 'expired')),
  created_at timestamptz not null default timezone('utc', now()),
  expires_at timestamptz not null default (timezone('utc', now()) + interval '15 minutes'),
  responded_at timestamptz,
  message text not null default '' check (char_length(message) <= 240)
);

create unique index if not exists idx_party_join_requests_pending_user
on public.party_join_requests (party_id, user_id)
where status = 'pending';

create index if not exists idx_party_join_requests_user
on public.party_join_requests (user_id, status, created_at desc);

create table if not exists public.party_activity_sessions (
  id uuid primary key default gen_random_uuid(),
  party_id uuid not null references public.parties (id) on delete cascade,
  activity text not null check (char_length(btrim(activity)) between 1 and 60),
  status text not null default 'active' check (status in ('active', 'completed', 'failed', 'cancelled')),
  started_by_user_id uuid not null references public.profiles (id) on delete cascade,
  member_snapshot jsonb not null default '[]'::jsonb,
  result_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  started_at timestamptz not null default timezone('utc', now()),
  ended_at timestamptz
);

create index if not exists idx_party_activity_sessions_party
on public.party_activity_sessions (party_id, started_at desc);

create table if not exists public.party_events (
  id bigint generated by default as identity primary key,
  party_id uuid references public.parties (id) on delete cascade,
  actor_user_id uuid references public.profiles (id) on delete set null,
  event_kind text not null check (char_length(btrim(event_kind)) between 1 and 60),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_party_events_party_time
on public.party_events (party_id, created_at desc);

drop trigger if exists set_parties_updated_at on public.parties;
create trigger set_parties_updated_at
before update on public.parties
for each row execute function public.set_updated_at();

drop trigger if exists set_party_members_updated_at on public.party_members;
create trigger set_party_members_updated_at
before update on public.party_members
for each row execute function public.set_updated_at();

create or replace function public.is_party_member(p_party_id uuid, p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.party_members pm
    where pm.party_id = p_party_id
      and pm.user_id = p_user_id
  );
$$;

create or replace function public.is_party_leader(p_party_id uuid, p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.party_members pm
    where pm.party_id = p_party_id
      and pm.user_id = p_user_id
      and pm.role = 'leader'
  );
$$;

create or replace function public.can_view_party(p_party_id uuid, p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.parties p
    where p.id = p_party_id
      and p.disbanded_at is null
      and (
        (p.visibility = 'open' and p.state = 'forming')
        or public.is_party_member(p.id, p_user_id)
        or exists (
          select 1
          from public.party_invites pi
          where pi.party_id = p.id
            and pi.to_user_id = p_user_id
            and pi.status = 'pending'
            and pi.expires_at > timezone('utc', now())
        )
        or exists (
          select 1
          from public.party_join_requests pjr
          where pjr.party_id = p.id
            and pjr.user_id = p_user_id
            and pjr.status = 'pending'
            and pjr.expires_at > timezone('utc', now())
        )
      )
  );
$$;

alter table public.parties enable row level security;
alter table public.party_members enable row level security;
alter table public.party_invites enable row level security;
alter table public.party_join_requests enable row level security;
alter table public.party_activity_sessions enable row level security;
alter table public.party_events enable row level security;

drop policy if exists "parties_select_visible" on public.parties;
create policy "parties_select_visible"
on public.parties
for select
to authenticated
using (public.can_view_party(id, auth.uid()));

drop policy if exists "party_members_select_visible" on public.party_members;
create policy "party_members_select_visible"
on public.party_members
for select
to authenticated
using (public.can_view_party(party_id, auth.uid()));

drop policy if exists "party_invites_select_sender_or_target" on public.party_invites;
create policy "party_invites_select_sender_or_target"
on public.party_invites
for select
to authenticated
using (
  auth.uid() = from_user_id
  or auth.uid() = to_user_id
  or public.is_party_leader(party_id, auth.uid())
);

drop policy if exists "party_join_requests_select_requester_or_leader" on public.party_join_requests;
create policy "party_join_requests_select_requester_or_leader"
on public.party_join_requests
for select
to authenticated
using (
  auth.uid() = user_id
  or public.is_party_leader(party_id, auth.uid())
);

drop policy if exists "party_activity_sessions_select_visible" on public.party_activity_sessions;
create policy "party_activity_sessions_select_visible"
on public.party_activity_sessions
for select
to authenticated
using (public.can_view_party(party_id, auth.uid()));

drop policy if exists "party_events_select_members" on public.party_events;
create policy "party_events_select_members"
on public.party_events
for select
to authenticated
using (party_id is not null and public.is_party_member(party_id, auth.uid()));
